
    prefix = "."
    stop-words = "stopwords.txt"

    dataset = "output"
    corpus = "line.toml"
    index = "news-articles-idx"
    
    [[analyzers]]
    method = "ngram-word"
    ngram = 1
    filter = "default-unigram-chain"
    